### PR TITLE
pt-BR

### PR DESCRIPTION
**Pull request by tiagocpontesp**
As always, feel free to leave out the less interesting one. 
It's in here mostly to share my notes and opinions with you.

This pt-BR should already be pretty good, but it's certainly not perfect (I'm from PT, not BR).
(Started with BR because of the auto-translator's tendencies.)

I'd suggest we get this one in so I can experience it on the interface. 
I'll then be able to make a few adjustments, and commit a perfect pt-PT.

### CODE REVIEW

**Comment by clehner** [comment]
Thanks for the first translation!

I replaced the TODOs/NOTEs with comments attempting to address them. Also I separated out the items that are for application-level things in the menubar on a Mac.

> suggestion: keeping literals relating to a particular type of thing to that thing's own named section. Some of these might not be as reusable as they first appear. Would also help with the translations (dealing w/ mandatory feminizations, conceptually, etc.)

I agree. However, I'm not sure exactly which strings that is most useful for. Would you be able to point out more such cases? I'm also wary of changing key names because it may require updating the module dependency in 15 modules, or breaking semver. However, this is not a problem before any ssb-patchwork npm release depends on the translations.

> perhaps important concept words, that are also typically anglicized should get capitalized everywhere. words like "peer" and "pub", though not "zoom".

That makes sense. I see pub is already capitalized in some places. Other places it is "pub server", "pub bot". I'm not sure what is best here.

> I'd suggest we get this one in so I can experience it on the interface

Are you running Patchwork from git, or npm, or ...?

**Comment by tiagocpontesp** [comment]
> Thanks for the first translation!

You're very welcome. 

> Are you running Patchwork from git, or npm, or ...?

ssbc/patchwork though the npm package currently.

> Would you be able to point out more such cases?
> However, this is not a problem before any ssb-patchwork npm release depends on the translations.

I'll might take another shot at these later today then.

> That makes sense. I see pub is already capitalized in some places. Other places it is "pub server", "pub bot". I'm not sure what is best here.

If there's no pre-established opinion on this I'll just throw my ideas in a commit.

**Comment by lucasexpresso** [comment]
Hi Guys, Dominic asked me to give you a hand, I'm Brazilian, though a complete rookie when it comes to code or Github. What is the best way for me to propose changes on the chosen terms? Would you guide me on how to fork it and then ask you for a pull request? I know the terms but not how to do it. It might be faster if you flick me an email, at lucasexpresso_gmail.
abraços

Lucas

**Comment by clehner** [comment]
Hi @lucasexpresso, thanks for joining in. One way to propose changes is to use GitHub's built-in editor. To propose changes to the pt-BR translation, you can go to the page for [pt-BR.js](https://github.com/ssbc/patchwork-translations/blob/master/locales/pt-BR.js) and there should be a pencil icon offering you the ability to edit the file. If you click that, I think GitHub will automatically fork the repo and give you an editor interface. Then you can edit and change the values, save your changes with a commit message, and I think GitHub will guide you to open a pull request with the changes. The source phrases in English are at [en.js](https://github.com/ssbc/patchwork-translations/blob/master/locales/en.js). You could also post changes in conversational form on the Issues here or in Patchwork.

**Comment by tiagocpontesp** [comment]
He left a PR on my repo: https://github.com/tiagocpontesp/patchwork-translations/pull/1
Do you know if we should distinguish "Fail"s from "Error"s?

**Comment by clehner** [comment]
Oh, nice.

To me, "Fail" connotes that some action was attempted and then didn't accomplish what it was supposed to, whereas "Error" means some generic technical problem happened. Looking at the strings though, I think it is basically interchangable whether something is called an error or a failure. "Failed to ..." could also be written "Unable to ..."

**Comment by tiagocpontesp** [comment]
@lucasexpresso Should I edit those "Unable to" to "Não foi possível"?
@clehner I'll PR both perfected PTs tomorrow, as well as a those capitalizations (e.g.: Peer, Pub). Sounds good?

**Comment by clehner** [comment]
@tiagocpontesp sounds good!

**Comment by lucasexpresso** [comment]
Thiago that is perfect. Thanks for the tips Cle.

**Pull request merged**
